---
name: Build & Push Docker Image

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

permissions:
  contents: read 
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          pull: true
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/caddy:latest
            ghcr.io/${{ github.repository_owner }}/caddy:${{ github.run_id }}

  prune-old-images:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    needs: []
    
    steps:
      - name: Delete old GHCR versions
        uses: actions/delete-package-versions@v5
        with:
          package-type: container
          package-name: caddy
          ignore-versions: latest
          min-versions-to-keep: 3
          token: ${{ secrets.GITHUB_TOKEN }}
