---
name: Build & Push Docker Image

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

permissions:
  contents: read 
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          pull: true
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/caddy:latest
            ghcr.io/${{ github.repository_owner }}/caddy:${{ github.run_id }}
          token: ${{ secrets.GITHUB_TOKEN }}
